//#pragma once
#include "Globals.h"

#ifdef GAME_OBJECT_IMPL
uint32 CompID = 0;
#define NW_COMPONENT_COMPILE_TIME_ID(comp) extern const uint32 comp##ID; const uint32 comp##ID = CompID++;
#else
#define NW_COMPONENT_COMPILE_TIME_ID(comp) extern const uint32 comp##ID;
#endif
NW_COMPONENT_COMPILE_TIME_ID(Transform);
NW_COMPONENT_COMPILE_TIME_ID(Sprite);
NW_COMPONENT_COMPILE_TIME_ID(ParticleSystem);
NW_COMPONENT_COMPILE_TIME_ID(AudioEmitter);
NW_COMPONENT_COMPILE_TIME_ID(MultiAudioEmitter);
NW_COMPONENT_COMPILE_TIME_ID(AudioListener);
NW_COMPONENT_COMPILE_TIME_ID(Camera);
NW_COMPONENT_COMPILE_TIME_ID(Script);
NW_COMPONENT_COMPILE_TIME_ID(Collider);
NW_COMPONENT_COMPILE_TIME_ID(CircleCollider);
NW_COMPONENT_COMPILE_TIME_ID(Text);
NW_COMPONENT_COMPILE_TIME_ID(DynamicScript);
NW_COMPONENT_COMPILE_TIME_ID(BatchExtra);
NW_COMPONENT_COMPILE_TIME_ID(LineRenderer);
NW_COMPONENT_COMPILE_TIME_ID(TriangleRenderer);
NW_COMPONENT_COMPILE_TIME_ID(CircleRenderer);
#undef NW_COMPONENT_COMPILE_TIME_ID
